site_name: SkinnyFE Docs
site_dir: ../../../build/distributions/docs

pages:
- Welcome: index.md
- User Guide:
    - Getting Started: GettingStarted.md
    - Configuration: Configuration.md
    - Examples: Examples.md
